### ISSUE TITLE
Peer review by Furqan Khan

### ISSUE THREAD

**Issue by fkhan72** [UBC-MDS/DSCI522_Group413_WhatHappensInVegas#26]
The feature selection looks good. Try adding more plots in the results section. Elaborate more on the model selection. In particular, how the model selection process was performed.

**Comment by arunmarria** [comment]
Thanks Furqan for valuable feedback. We will definitely work on these suggestions.

**Comment by arunmarria** [comment]
Elaborated and added detailed explanation.

**Comment by arunmarria** [comment]
#29
