### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by bbaillie** [UBC-MDS/DSCI522_Group413_WhatHappensInVegas#27]
Change the title back to what it was supposed to be (capitalize Vegas, include user)

Discussion in our results about whether or not our model was actually good,
- consider looking into the parameters, ands interpreting the model 

Discuss use of using MSE to measure performance - how does it relate to our goal?

**Comment by bbaillie** [comment]
Include the model we used with RFE in the discussion of that

**Comment by bbaillie** [comment]
Make a residual plot to show how are model was performing?

**Comment by arunmarria** [comment]
yeah residual plot might be  a good idea

**Comment by arunmarria** [comment]
Plots added #33
