### ISSUE TITLE
Visualization Feedback

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI522_Group413_WhatHappensInVegas#37]
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- - [ ] Great job adding figure numbers and captions! Though your captions could have been a bit more informative, overall this is a very good practice. 
- - [ ] Figure 1:
	- - [ ] Looks great! But It's not immediately clear what I'm look at here. With a score of 1, on the x-axis is the number of helpful votes, but what's on the y-axis? It's possible I'm not understanding here what you're showing
- - [ ] Figure 2: 
	- - [ ] It's not correct to show a distribution for the scores, because the possible values are only 1,2,3,4,or 5; the distribution implies there are middle values are possible
- - [ ] Figure 3 and 4:
	- - [ ] Figure 2 is repeated labeled twice
	- - [ ] This plot is good and shows what you want it to, but it's a little large
	- - [ ] You should probably do a side-by-side plot of Fig 3 and Fig 4
- - [ ] Overall, great work! I think your tables and figure overall are very reasonable for your project and well-selected.

**Comment by arunmarria** [comment]
#38  resized images and corrected labels
