### ISSUE TITLE
Release version for milestone 1. 

### ISSUE THREAD

**Issue by arunmarria** [UBC-MDS/DSCI522_Group413_WhatHappensInVegas#8]
AS per requirements,

"Create a release on your project repo named v1.0 and submit that URL in your milestone1 repo's README.md file so we know where to find it."

Creating a placeholder so we dont forget to create a release with version 1.0 
as we will need to use that url for our private milestone 1 repos. 

This should be the last step after all other 4 issues are closed.

**Comment by bbaillie** [comment]
I don't know how to formally do this myself, anyone able to walk me through it?

**Comment by arunmarria** [comment]
Thanks we have a release now!
